"""alter

Revision ID: 08e17794eabd
Revises: ff3b8cbe20b7
Create Date: 2025-07-17 22:41:30.640515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e17794eabd'
down_revision = 'ff3b8cbe20b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###