"""update_victory_conditions_to_json

Revision ID: d0d55c21dccb
Revises: 08e17794eabd
Create Date: 2025-07-19 15:16:48.999905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d55c21dccb'
down_revision = '08e17794eabd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 需要使用 USING 子句来转换 TEXT 到 JSON
    # 将现有的文本数据包装成 JSON 格式
    op.execute("""
        ALTER TABLE background_stories 
        ALTER COLUMN victory_conditions 
        TYPE JSON 
        USING CASE 
            WHEN victory_conditions IS NULL OR victory_conditions = '' THEN '{}'
            WHEN victory_conditions ~ '^\\s*[\\{\\[]' THEN victory_conditions::json
            ELSE json_build_object('description', victory_conditions)
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 将 JSON 转换回 TEXT
    op.execute("""
        ALTER TABLE background_stories 
        ALTER COLUMN victory_conditions 
        TYPE TEXT 
        USING victory_conditions::text
    """)
    # ### end Alembic commands ###