"""ini

Revision ID: ff3b8cbe20b7
Revises: 
Create Date: 2025-07-17 22:30:28.369119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3b8cbe20b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='scriptstatus'), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('setting_description', sa.Text(), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('victim_background', sa.Text(), nullable=True),
    sa.Column('investigation_scope', sa.Text(), nullable=True),
    sa.Column('rules_reminder', sa.Text(), nullable=True),
    sa.Column('murder_method', sa.String(length=100), nullable=True),
    sa.Column('murder_location', sa.String(length=255), nullable=True),
    sa.Column('discovery_time', sa.String(length=100), nullable=True),
    sa.Column('victory_conditions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_murderer', sa.Boolean(), nullable=True),
    sa.Column('is_victim', sa.Boolean(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('voice_preference', sa.String(length=50), nullable=True),
    sa.Column('voice_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_to', sa.String(length=100), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=20), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('BACKGROUND', 'INTRODUCTION', 'EVIDENCE_COLLECTION', 'INVESTIGATION', 'DISCUSSION', 'VOTING', 'REVELATION', 'ENDED', name='gamephaseenum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('searchable_items', sa.JSON(), nullable=True),
    sa.Column('background_image_url', sa.Text(), nullable=True),
    sa.Column('is_crime_scene', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('game_phases')
    op.drop_table('evidence')
    op.drop_table('characters')
    op.drop_table('background_stories')
    op.drop_table('scripts')
    # ### end Alembic commands ###